package main

import (
	"bufio"
	"bytes"
	"compress/gzip"
	_ "embed"
	"log"
	"net"
	"strings"
	"sync"
)

// ouiData is the IEEE registry of MAC address prefixes, generated by
// ./tools/genoui and compressed to keep the binary small. Regenerate it with:
//
//	go run ./tools/genoui
//
//go:embed data/oui.gz
var ouiData []byte

var (
	ouiOnce  sync.Once
	ouiTable map[string]string
)

// loadOUI decompresses the embedded table on first use. Around 54,000 entries
// cost a few milliseconds and a handful of megabytes, so it is not worth
// paying for on startup if nothing ever scans.
func loadOUI() {
	ouiTable = map[string]string{}

	reader, err := gzip.NewReader(bytes.NewReader(ouiData))
	if err != nil {
		log.Printf("Could not read the manufacturer table: %v", err)
		return
	}
	defer reader.Close()

	scanner := bufio.NewScanner(reader)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		prefix, vendor, found := strings.Cut(scanner.Text(), "\t")
		if !found || prefix == "" || vendor == "" {
			continue
		}
		ouiTable[prefix] = vendor
	}
	if err := scanner.Err(); err != nil {
		log.Printf("Could not read the manufacturer table: %v", err)
	}
	log.Printf("Loaded %d manufacturer prefixes", len(ouiTable))
}

// vendorForMAC identifies the manufacturer that owns a MAC address.
//
// The IEEE hands out address blocks in three sizes, so the longest assignment
// is checked first: MA-S covers 36 bits, MA-M 28 bits and MA-L the classic
// 24-bit OUI. Without that order a MAC inside a small block would be credited
// to whichever company owns the surrounding 24-bit range.
func vendorForMAC(mac string) string {
	hw, err := net.ParseMAC(mac)
	if err != nil || len(hw) != 6 {
		return ""
	}

	ouiOnce.Do(loadOUI)

	hex := strings.ToUpper(strings.ReplaceAll(mac, ":", ""))
	for _, length := range []int{9, 7, 6} {
		if len(hex) < length {
			continue
		}
		if vendor, ok := ouiTable[hex[:length]]; ok {
			return vendor
		}
	}

	// Locally administered addresses are randomised by the device rather than
	// assigned by a manufacturer, so no lookup can ever succeed. Phones do this
	// by default on Wi-Fi, and the address changes between networks.
	if hw[0]&0x02 != 0 {
		return "Randomised address"
	}
	return ""
}
